USE ships
-- Намерете
-- имената на
-- битките, в които
-- са участвали
-- поне 3 кораба с
-- под 9 оръдия и от
-- тях поне два са с
-- резултат ‘ok’.

SELECT OUTCOMES.BATTLE
FROM OUTCOMES 
JOIN SHIPS ON OUTCOMES.SHIP = SHIPS.NAME
JOIN CLASSES ON CLASSES.CLASS = SHIPS.CLASS 
WHERE CLASSES.NUMGUNS <= 9
GROUP BY OUTCOMES.BATTLE
HAVING COUNT(*) >= 3 
AND 
SUM(CASE WHEN OUTCOMES.RESULT = 'ok' THEN 1 ELSE 0 END) >= 2;

SELECT o.BATTLE
FROM OUTCOMES o
	JOIN SHIPS s ON o.SHIP = s.NAME
	JOIN CLASSES c ON s.CLASS = c.CLASS
GROUP BY o.BATTLE
HAVING SUM(CASE WHEN c.NUMGUNS <= 9 THEN 1 ELSE 0 END) >= 3
	AND SUM(CASE WHEN c.NUMGUNS <= 9 AND o.RESULT = 'ok' THEN 1 ELSE 0 END) >= 2;